watch-src:
	bacon run

# Syntax:
# bacon test -- --test <filename-inside-the-tests-folder> <function-name-inside-test-file> -- --nocapture
# The `-- --nocapture` part will allow the output of println statements to pass through to the terminal.
watch-tests:
	bacon test -- --test quick_dev quick_dev -- --nocapture
